sudo: required
services :
    - docker

before_install:
    - docker build -t shwetabhuria/docker-react -f Dockerfile.dev .
    
#script:
 #   - docker run shwetabhuria/docker-react npm run test -- -- coverage    