sudo: required
services :
    - docker

before_install:
    - docker build -t shwetabhuria/docker-react -f Dockerfile.dev .
    
script:
    - "docker run -e CI=true shwetabhuria/docker-react npm run test -- --coverage" 
 
